// These are the OOTB system columns that exist on every PP table.
// Update the list to columns you want to exclude, clear the set of columns if you want to include them all
export const DEFAULT_EXCLUDED_COLUMNS = new Set([
  'timezoneruleversionnumber',
  'utcconversiontimezonecode',
  'importsequencenumber',
  'overriddencreatedon',
  'exchangerate',
  'transactioncurrencyid',
  'owningteam',
  'owninguser',
  'owningbusinessunit',
  'createdonbehalfby',
  'modifiedonbehalfby',
  'versionnumber',
]);
// Auto-generated by PP for every money column
export const DEFAULT_EXCLUDE_BASE_CURRENCY_FIELDS = true;

// Standard system relationships that exist on every table 
export const DEFAULT_EXCLUDE_STANDARD_RELATIONSHIPS = false;

// Form output rendering options
export const RENDER_OPTIONS = {
  // 'detailed' shows tabs, sections and fields per form
  // 'compact' shows summary table only
  // !!!comment the lines out accordingly so there is only one uncommented!!!

  // formLayout: 'detailed' as 'detailed' | 'compact', // this will enforce detailed
  formLayout: 'compact' as 'detailed' | 'compact', // this will enforce compact
};